c3d/src/main/java/com/expeditors/training/course3demo/model/Card.java
package com.expeditors.training.course3demo.model;

import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.NotBlank;

public class Card {
	String name;
	
	@NotBlank
	@Pattern(regexp="(\\d{4}\\-?){3}\\d{4}")
	String number;
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = formatAsCreditCard(number);
	}
	public String getMaskedNumber() {
		return maskCreditCardNumber(number);
	}
	
	String maskCreditCardNumber(String str) {
		return
				str
				.substring(
						0,
						str.length() - 4)
				.replaceAll("\\d", "*") + 
				str.substring(
						str.length() - 4,
						str.length());
	}
	
	String formatAsCreditCard(String str) {
		String digits = str.replaceAll("[^\\d]", "");
		StringBuilder sb = new StringBuilder();
		
		for (int i = 0; i < digits.length();) {
			sb.append(digits.charAt(i++))
			.append((i % 4 == 0 && i < digits.length()) ? '-' : "");
		}
		
		return sb.toString();
	}
}

c3d/src/main/java/com/expeditors/training/course3demo/model/Product.java
package com.expeditors.training.course3demo.model;

import org.hibernate.validator.constraints.NotEmpty;

public class Product {
	long id;
	
	@NotEmpty
	String name;
	
	
	String description;
	
	
	double price;
	
	
	public Product() {}
	public Product(long id, String name, String description, double price) {
		super();
		this.id = id;
		this.name = name;
		this.description = description;
		this.price = price;
	}
	public Product(String name, String description, double price) {
		super();
		this.name = name;
		this.description = description;
		this.price = price;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
}

c3d/src/main/java/com/expeditors/training/course3demo/controller/CardController.java
package com.expeditors.training.course3demo.controller;

import java.util.List;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.web.bind.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.expeditors.training.course3demo.model.Card;

@Controller
@RequestMapping("/card/")
public class CardController {
	Logger logger = LoggerFactory.getLogger(CardController.class);
	
	@RequestMapping("add.html")
	public ModelAndView showAddCard(
			@AuthenticationPrincipal User activeUser) {
		ModelAndView mav = new ModelAndView();
		mav.addObject("card", new Card());
		mav.setViewName("addCard");
		return mav;
	}
	
	@RequestMapping(method=RequestMethod.POST, value="add.html")
	public ModelAndView doAddCard(@ModelAttribute @Valid Card card,
			BindingResult result,
			Model m) {
		ModelAndView mav = new ModelAndView();
		mav.addObject("card", card);
		List<ObjectError> coll = result.getAllErrors();
		logger.info("card name: " + card.getName());
		logger.info("card number: " + card.getNumber());
		for (ObjectError oe : coll) {
			logger.info(oe.toString());
		}
		mav.setViewName( result.hasErrors() ? "addCard" : "showCard" );
		return mav;
	}
	
}

c3d/src/main/java/com/expeditors/training/course3demo/controller/ProductController.java
package com.expeditors.training.course3demo.controller;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import com.expeditors.training.course3demo.model.Product;
import com.expeditors.training.course3demo.service.ProductService;

@Controller
@RequestMapping("/product/")
public class ProductController {
	private static final Logger logger = LoggerFactory.getLogger(ProductController.class);
	
	@Autowired
	private ProductService service;
	
	@RequestMapping(method=RequestMethod.GET, value="show.html")
	public ModelAndView showProduct(@RequestParam("product_id") long id) {
		ModelAndView mav = new ModelAndView();
		mav.setViewName("showProduct");
		logger.debug("Setting name to Tea");
		mav.addObject("product", service.getProduct(id));
		return mav;
	}
	
	@RequestMapping(method=RequestMethod.GET, value="add.html")
	public ModelAndView addProduct() {
		ModelAndView mav = new ModelAndView();
		mav.setViewName("addProduct");
		Product product = new Product();
		product.setPrice(2.99);
		mav.addObject("product", product);
		return mav;
	}
	
	@RequestMapping(method=RequestMethod.POST, value="add.html")
	public ModelAndView addProduct(@ModelAttribute("product") @Valid Product product,
			BindingResult result,
			Model m) {
		ModelAndView mav = new ModelAndView();
		mav.addObject("product", product);
		
		mav.setViewName(result.hasErrors() ? "addProduct" : "showProduct");
		
		return mav;
	}
	
}

c3d/src/main/webapp/WEB-INF/view/addCard.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
	<title>Add a Card for <sec:authentication property='principal.username' /></title>
</head>
<body>
<form:form method="POST" commandName="card">
	<table>
		<tr>
			<td>Name:</td>
			<td><form:input path="name"/></td>
			<td><form:errors path="name" cssClass="error"/></td>
		</tr>
		<tr>
			<td>Number:</td>
			<td><form:input path="number"/></td>
			<td><form:errors path="number" cssClass="error"/></td>
		</tr>
		<tr>
			<td colspan="2"><input type="submit" value="Add Card"/></td>
		</tr>
	</table>
</form:form>
</body>
</html>

c3d/src/main/webapp/WEB-INF/view/addProduct.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Add a Product</title>
<link rel="stylesheet" type="text/css" href='<c:url value="/static/css/my.css" />' />
</head>
<body>
<form:form method="POST" commandName="product">
	<div class="container">
		<div class="row">
			<p class="medium-6 small-text-center medium-text-right columns">Name:</p>
			<p class="small-6 small-offset-3 medium-offset-0 medium-3 columns">
				<form:input path="name" />
			</p>
			<p class="medium-3 columns" style="color:red"><form:errors path="name" cssClass="error" /></p>
		</div>
		<div class="row">
			<p class="medium-3 small-text-center medium-offset-3 medium-text-right columns">Description:</p>
			<p class="medium-3 medium-pull-3 columns">
				<form:input path="description" />
			</p>
		</div>
		<div class="row">
			<p class="medium-3 medium-offset-3 medium-text-right columns">Price:</p>
			<p class="small-6 small-pull-3 medium-3 medium-pull-3 columns">
				<form:input style="text-align:center" path="price" />
			</p>
		</div>
		<div class="row">
			<p class="small-3 small-centered columns">
				<input type="submit" class="button" value="Add Product" />
			</p>
		</div>
	</div>
</form:form>
</body>
</html>

c3d/src/main/webapp/WEB-INF/view/showCard.jsp
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page language="java" %>
<!DOCTYPE html>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    
<html>
	<head>
		<title>Card Info: ${card.name}</title>
	</head> 
	<body>
		<h2>${card.name}</h2>
		<p>${card.maskedNumber}</p>
	</body>
</html>

c3d/src/main/webapp/WEB-INF/view/showProduct.jsp
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page language="java" %>
<!DOCTYPE html>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    
<html>
	<head>
		<title>Product Info: ${product.name}</title>
	</head> 
	<body>
		<h2>${product.name} - <fmt:formatNumber type="currency" value="${product.price}" /></h2>
		<p>${product.description}</p>
	</body>
</html>

c3d/src/main/webapp/decorators/basic-theme.jsp
<%@ taglib uri="http://www.opensymphony.com/sitemesh/decorator" prefix="decorator" %>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><decorator:title /></title>
</head>
<body>
    <h1><decorator:title /></h1>
    <p><b>Navigation</b></p>
    <hr />
    <decorator:body />
    <hr />
    <h2><decorator:title /></h2>
    <p>&copy; Expeditors International Training</p>
</body>
</html>

c3d/src/main/webapp/decorators/my-theme.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.opensymphony.com/sitemesh/decorator" prefix="decorator" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:url value="/static/css/foundation.min.css" var="foundation_css" />
<c:url value="/static/js/vendor/modernizr.js" var="modernizr_js" />

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<decorator:head />
	<title><decorator:title /></title>
	
	<!-- stylesheets -->
	<link rel="stylesheet" href="${foundation_css}" />
	
	<!-- preloaded scripts -->
	<script type="text/javascript" src="${modernizr_js}"></script>
</head>
<body>
	<header class="row">
	    <h1 class="small-text-center"><decorator:title /></h1>
	</header>
    <hr />
    <decorator:body />
    <hr />
    <footer class="row">
	    <p class="small-text-center">&copy; 2015 Expeditors Training</p>
    </footer>
</body>
</html>

c3d/src/main/webapp/index.jsp
<!DOCTYPE html>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<html>
	<head>
		<meta charset="utf-8">
		<title>Welcome</title>
	</head> 
	<body>
		<c:url value="/product/show" />
		<a href="<c:url value="/product/show.html?product_id=1" />" >Click to enter</a>
	</body>
</html>